### ISSUE TITLE
Feature request: Export parseScript and opcode fields

### ISSUE THREAD

**Issue by jonasnick** [btcsuite/btcscript#28]
Thank you for creating and maintaining btcscript.
As far as I can see, there is currently no possibility for external packages to parse the bytes from btcwire.MsgTx.TxOut[i].PkScript to an array of opcodes. The function parseScript achieves that, but is not exported.
In order to further process the script it is necessary that the fields of opcode and parsedOpcode are accessible.
Example of what could be possible:
```go
func printScriptPubkey(txOut *btcwire.TxOut) {
	scriptPubkey, _ := btcscript.ParseScript(txOut.PkScript)

	for _, op := range scriptPubkey {
		log.Println(op.Opcode.Name)
	}
}

```

**Comment by davecgh** [comment]
This has been moved to btcsuite/btcd#267.
